# Use a imagem oficial do .NET como base para o runtime
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use a imagem oficial do .NET SDK para o build
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["LP_API/LP_API.csproj", "./"]
RUN dotnet restore "./LP_API.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "LP_API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LP_API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LP_API.dll"]